name: Python Unittests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  python_matrix:
    strategy:
        matrix:
            version: ['3.10', '3.11', "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
    - name: Install test runner (tox)
      run: |
        python -m pip install --upgrade pip
        python -m pip install "tox>=4.22"
    - name: Test with tox
      run: tox
